#!/bin/bash
# echo noop > /sys/block/sda/queue/scheduler
# sector_read
modprobe sstf-iosched
echo sstf > /sys/block/sda/queue/scheduler
sector_read
echo cfq > /sys/block/sda/queue/scheduler
dmesg > out.txt